### ISSUE TITLE
LHS > conditions > constraints

### ISSUE THREAD

**Issue by alex-dixon** [cursive-ide/clara-specs#1]
I like the way rules and queries are defined [here](https://github.com/cerner/clara-rules/blob/1eeda639942ad16fb0582c6b607af117afa59a57/src/test/clojurescript/clara/test_rules_data.clj#L6):
```
[{:doc "Rule to determine whether it is indeed cold and windy."
    :name "clara.test-rules-data/is-cold-and-windy-data"
    :lhs '[{:type clara.rules.testfacts/Temperature
            :constraints [(< temperature 20)
                          (== ?t temperature)]}
           {:type clara.rules.testfacts/WindSpeed
            :constraints [(> windspeed 30)
                          (== ?w windspeed)]}]
    :rhs '(clara.rules/insert! (clara.rules.testfacts/->ColdAndWindy ?t ?w))}

   {:name "clara.test-rules-data/find-cold-and-windy-data"
    :lhs '[{:fact-binding :?fact
            :type clara.rules.testfacts/ColdAndWindy
            :constraints []}]
    :params #{}}])
```

It's very similar to the data structure generated by Clara's tracing/reporting used for rule explanations, and I think it's used internally in the engine.

The way I read it: 
1. A LHS is comprised of conditions 
2. Conditions are comprised of a fact type and constraints. 
3. Constraints are functions that return true or false, taking any number of `any?` parameters.

From [clara-examples/validation](https://github.com/cerner/clara-examples/blob/78389921e843daeb5cd4afe91cc42b3bb9cecce7/src/main/clojure/clara/examples/validation.clj#L23):

Example LHS:
```
  [WorkOrder (= ?clientid clientid)
             (= scale :big)
             (< (days-between requestdate duedate) 14)] 
  [:not [ClientTier
         (= ?clientid id) ; Join to the above client ID.
         (= tier :top)]]
```

Example condition:
```
[WorkOrder (= ?clientid clientid)
             (= scale :big)
             (< (days-between requestdate duedate) 14)] 
```

Note: @cmf has already accounted for `:fact-bindings`, which are optional. If we had the rule:
```
  [?my-fact-binding <- WorkOrder (= ?clientid clientid)
             (= scale :big)
             (< (days-between requestdate duedate) 14)] 
```

The data structure above would look like:
```
:lhs '[{:type clara.rules.testfacts/Temperature
          :fact-binding ?my-fact-binding
            :constraints [(< temperature 20)
                          (== ?t temperature)]}]
```
So the fact-binding is part of the "condition".

Example constraint:
```
(= scale :big)
```
A constraint is commonly `(= scale :big)` but a valid constraint is also `(< (days-between requestdate duedate) 14)`, or `(my-predicate-fn 42 duedate ?clientid)`

Overall I like this way of structuring things so putting it out there for consideration.

I am concerned we may not be able to define a valid constraint if we're working at the macro/symbol level only, but this seems something we'd encounter no matter how the specs are structured and what terms we use for the syntax.

**Comment by cursive-ide** [comment]
That does look nice - I'll try to structure the specs so that conforming produces data in that format.
