### ISSUE TITLE
Accumulator conditions don't require a result binding

### ISSUE THREAD

**Issue by WilliamParker** [cursive-ide/clara-specs#3]
The following rule compiles and runs:

````
(defrule myrule [(acc/all) :from [Object]] => (println "hi"))
(-> (mk-session [myrule]) fire-rules)
;; prints hi
````

The [existing schema](https://github.com/cerner/clara-rules/blob/992d924681cf36e1d4b275854b99ddb79b71d09e/src/main/clojure/clara/rules/schema.cljc#L39) doesn't require a result binding.  In most (almost all?) use cases for accumulators you'll care about the result binding, but I can envision cases where this wouldn't be the case, e.g. where the [:convert-return-fn](https://github.com/cerner/clara-rules/blob/0.16.1/src/main/clojure/clara/rules/accumulators.cljc#L20) of the accumulator was a predicate that could return nil, preventing the accumulator condition from matching.

It looks to me like the spec currently requires that a result binding exist though.

````
(s/def ::accumulator (s/and vector?
                            (s/cat :binding-var ::variable-name
                                   :sep #{'<-}
                                   :fact-type any?
                                   :_ #{:from}
                                   :fact-expr ::fact-expr)))

(s/def ::condition (s/or :accumulator ::accumulator
                         :fact-expr ::fact-expr
                         :boolean-expr ::boolean-expr
                         :test ::test))
````

I just started looking at this spec and thought an issue would be an appropriate place to put distinct nontrivial thoughts, but let me know if there's another way you'd rather discuss.

**Comment by alex-dixon** [comment]
TIL. Will change PR #2 to reflect and think about using accumulators the way you describe.

**Comment by cursive-ide** [comment]
Thanks @WilliamParker, the [doc](http://www.clara-rules.org/docs/accumulators/) suggests that it's required but it looks like not. Once we get the specs nailed down hopefully it'll be relatively simple to generate those railroad diagrams from them.
