### ISSUE TITLE
fact-expr is ambiguous

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/clara-specs#4]
Currently the spec for `fact-expr` is as follows:

```
(s/def ::fact-expr (s/and vector?
                          (s/cat :binding (s/? (s/cat :binding-var ::variable-name
                                                      :sep #{'<-}))
                                 :fact-type any?
                                 :destructured-fact (s/? ::destructured)
                                 :expressions (s/* any?))))
```

This is horribly ambiguous due to the use of `any?` and optional elements. [Here](https://github.com/cursive-ide/clara-specs/blob/fa9f7aca57b7a4735d356f54e22399efc4534f72/test/clara_specs/core_test.clj#L49-L50) is a result of a bad parse that I hadn't noticed earlier. The example is: 

```
[?temp <- [Temperature (= ?location location)]]
``` 

Here are a couple of possible parses for this with the given spec:

```
{:binding {:binding-var ?temp :sep <-}
 :fact-type [Temperature (= ?location location)]}
```

```
{:fact-type   ?temp
 :expressions [<-
               [Temperature (= ?location location)]]}
```

Can we restrict these patterns any further? I guess that there should always be at least one expression, are the expressions always lists? Can `fact-type` be restricted further than just `any?`.

**Comment by mrrodriguez** [comment]
I responded to this on the #clara Slack channel, but realized it'd be better to do that here. So I'll paste here:

Yeah, I can see where that is difficult and yes the “fact type” being anything makes things complicated. I’m pretty sure you can break Clara parsing if you try to use a fact type that seems too much like something else.

One thing that is interesting and probably should be part of the spec (I don’t believe it is now), is that variable bindings should always start with “?”. So in the case of the fact binding, it is the `::variable-binding` from this spec.

And perhaps we should just list a few things that a fact type should not be, like it shouldn’t be a symbol that starts with a “?”. I think it may not be ok for it to be a vector either. I seem to recall a bad parse example from long back where a fact type as a vector would mess up things.

**Comment by WilliamParker** [comment]
- Hopefully I can circle back on this later, but a quick note - the reason the fact-type schema has to be so loose is that it actually can be almost anything.  Clara allows users to provide an arbitrary function used to determine the type of facts as well as an arbitrary function to determine the ancestors of those types determined.  These are the :fact-type-fn and the :ancestors-fn described in the [mk-session docstring](https://github.com/cerner/clara-rules/blob/0.16.1/src/main/clojure/clara/rules.cljc#L321).  These two functions provide the power to essentially create your own type system that Clara will use for rule/query dispatch.

- One hole in this that comes to mind is that if the fact type is a class, then Clara will assume that facts provided to the condition are of that class and allow reference to fields on that class by name.  If you had a :fact-type-fn like 

````
(fn [fact] (cond (instance? SomeClass fact) ClassWithDifferenceFields ....)
````

that would confuse Clara I think.

- If Clara is failing with a fact type that is itself a vector that actually seems like it would be a bug in Clara to me, although maybe we can't parse effectively in some case(s) with that?  Do you have an example in mind @mrrodriguez ?

**Comment by mrrodriguez** [comment]
@WilliamParker 
I know that essentially "anything" can be a fact type in theory due to the extension point functions you mentioned. However, I think it is fair to constrain it at some reasonable level. Especially since I think some forms may have direct clashes with parsing. 
In terms of a spec, I think perhaps we could focus on what it can't be instead of what it can be. However, I'm not sure hwo to do that still.

You call out a good point on Clara and field reflection as one thing. The vector case I believe is 
this one https://github.com/cerner/clara-rules/issues/65#issuecomment-54157846

Somewhat related is
https://github.com/cerner/clara-rules/issues/103

**Comment by cursive-ide** [comment]
One thing which would restrict this somewhat and prevent one of the erroneous parses above would be to use:
```
(s/or
  :with-binding (s/cat :binding-var ::variable-name
                       :sep #{'<-}
                       :fact-type any?
                       :destructured-fact (s/? ::destructured)
                       :expressions (s/* any?))
  :no-binding (s/cat :fact-type any?
                     :destructured-fact (s/? ::destructured)
                     :expressions (s/* any?)))
```
This takes advantage of the fact that spec alternates give priority to the earlier cases, so this will cause the rule to always use the binding if it is present. That is always what you want I think. Unfortunately it makes the conformed data weird by putting it inside a map with either `:with-binding` or `:no-binding` keys - spec doesn't provide enough control over the parsing here.

One other thing which would help - I assume that `:expressions` should use `s/+`, i.e. that there should always be at least one expression?

**Comment by mrrodriguez** [comment]
@cursive-ide 
>One other thing which would help - I assume that :expressions should use s/+, i.e. that there should always be at least one expression?

Unfortunately it there can be 0 `:expressions`. So no help there.
The `s/or` does seem to solve it, although it has the issues you mentioned. That extra map layer isn't necessarily that bad though if the key makes it clear what it is for.

Out of curiosity: Is that `s/or` behavior an implementation detail or something that should always be the case - i.e. preference to the first match.

**Comment by alex-dixon** [comment]
Not sure if the latest addresses this. If not maybe something like https://github.com/cursive-ide/clara-specs/blob/master/src/clara_specs/core.clj#L33?

**Comment by cursive-ide** [comment]
> Out of curiosity: Is that s/or behavior an implementation detail or something that should always be the case - i.e. preference to the first match.

That's defined (from [the doc](https://clojure.github.io/spec.alpha/clojure.spec.alpha-api.html#clojure.spec.alpha/or)):

> Returns a destructuring spec that returns a map entry containing the
key of the first matching pred and the corresponding value.

It's unfortunate that spec doesn't allow operators to be specified as greedy or not. Some regexp algorithms allow this (without backtracking), but spec does not.

**Comment by cursive-ide** [comment]
I'm curious, what does a `fact-expr` with 0 expressions look like? Something like `[?temp <- [Temperature]]` or even just `[[Temperature]]`? If there is no binding, is at least one expression required then?

**Comment by mrrodriguez** [comment]
@cursive-ide 
So here are some rule condition examples:
```clj
[?a <- A (= ?id id)]
[?b <- B]
[C]
[D (= ?id id)]
[E (= ?id id) (< v 10)]
[?fs <- (acc/all) :from [F]]
[?gs <- (acc/all) :from [G (< v 10)]]
[:test (< 2 (count ?gs))]
```
etc.

**Comment by WilliamParker** [comment]
Mike's condition examples above look comprehensive; I don't have anything to add to them.  To clarify the logical meaning, a condition with just a fact type and no constraints means that the rule will simply evaluate whether a fact of the type is present (and potentially fire more than once if more than one of the fact is present although this can be prevented using the :exists operator).

**Comment by mrrodriguez** [comment]
@WilliamParker well you mentioned one that I forgot there
```
[:exists [A]]
```

**Comment by cursive-ide** [comment]
Which condition alternate would `:exists` fall under? Is that considered a boolean expression operator?

Also, @alex-dixon, I see you added `'or`, `'and`, `'not` and `'exists` as potential ops - can these also be the symbol equivalents as well as the keywords?

**Comment by cursive-ide** [comment]
I believe the original issue (ambiguity) has been adequately addressed by the recent changes in the repo, so I'll close this for now.
